name: CI con Self-Hosted Runner

on:
  push:
    branches:
      - deploy/prueba1

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Make start.sh executable
        run: chmod +x start.sh

      - name: Run start.sh script
        run: ./start.sh
